// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package store

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, really_long_url)
VALUES ($1, $2)
RETURNING id, original_url, really_long_url, create_time, update_time
`

type CreateLinkParams struct {
	OriginalUrl   string `db:"original_url" json:"original_url"`
	ReallyLongUrl string `db:"really_long_url" json:"really_long_url"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ReallyLongUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ReallyLongUrl,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, really_long_url, create_time, update_time FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ReallyLongUrl,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getLinkByOriginalUrl = `-- name: GetLinkByOriginalUrl :one
SELECT id, original_url, really_long_url, create_time, update_time FROM links WHERE original_url = $1
`

func (q *Queries) GetLinkByOriginalUrl(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByOriginalUrl, originalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ReallyLongUrl,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getLinkByReallyLongUrl = `-- name: GetLinkByReallyLongUrl :one
SELECT id, original_url, really_long_url, create_time, update_time FROM links WHERE really_long_url = $1
`

func (q *Queries) GetLinkByReallyLongUrl(ctx context.Context, reallyLongUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByReallyLongUrl, reallyLongUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ReallyLongUrl,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, really_long_url, create_time, update_time FROM links
ORDER BY create_time DESC
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ReallyLongUrl,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = $2, really_long_url = $3
WHERE id = $1
RETURNING id, original_url, really_long_url, create_time, update_time
`

type UpdateLinkParams struct {
	ID            int64  `db:"id" json:"id"`
	OriginalUrl   string `db:"original_url" json:"original_url"`
	ReallyLongUrl string `db:"really_long_url" json:"really_long_url"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ReallyLongUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ReallyLongUrl,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}
