// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package store

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, really_long_path, really_long_query)
VALUES ($1, $2, $3)
RETURNING id, original_url, create_time, update_time, really_long_path, really_long_query
`

type CreateLinkParams struct {
	OriginalUrl     string `db:"original_url" json:"original_url"`
	ReallyLongPath  string `db:"really_long_path" json:"really_long_path"`
	ReallyLongQuery string `db:"really_long_query" json:"really_long_query"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ReallyLongPath, arg.ReallyLongQuery)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ReallyLongPath,
		&i.ReallyLongQuery,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, create_time, update_time, really_long_path, really_long_query FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ReallyLongPath,
		&i.ReallyLongQuery,
	)
	return i, err
}

const getLinkByOriginalUrl = `-- name: GetLinkByOriginalUrl :one
SELECT id, original_url, create_time, update_time, really_long_path, really_long_query FROM links WHERE original_url = $1
`

func (q *Queries) GetLinkByOriginalUrl(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByOriginalUrl, originalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ReallyLongPath,
		&i.ReallyLongQuery,
	)
	return i, err
}

const getLinkByReallyLongPath = `-- name: GetLinkByReallyLongPath :one
SELECT id, original_url, create_time, update_time, really_long_path, really_long_query FROM links WHERE really_long_path = $1
`

func (q *Queries) GetLinkByReallyLongPath(ctx context.Context, reallyLongPath string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByReallyLongPath, reallyLongPath)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.CreateTime,
		&i.UpdateTime,
		&i.ReallyLongPath,
		&i.ReallyLongQuery,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, create_time, update_time, really_long_path, really_long_query FROM links
ORDER BY create_time DESC
LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.CreateTime,
			&i.UpdateTime,
			&i.ReallyLongPath,
			&i.ReallyLongQuery,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
