// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID              int64              `db:"id" json:"id"`
	OriginalUrl     string             `db:"original_url" json:"original_url"`
	CreateTime      pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime      pgtype.Timestamptz `db:"update_time" json:"update_time"`
	ReallyLongPath  string             `db:"really_long_path" json:"really_long_path"`
	ReallyLongQuery string             `db:"really_long_query" json:"really_long_query"`
	PathHash        string             `db:"path_hash" json:"path_hash"`
}
