// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         int64              `db:"id" json:"id"`
	Username   string             `db:"username" json:"username"`
	IsAdmin    bool               `db:"is_admin" json:"is_admin"`
	CreateTime pgtype.Timestamptz `db:"create_time" json:"create_time"`
	UpdateTime pgtype.Timestamptz `db:"update_time" json:"update_time"`
}
