// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	GetLink(ctx context.Context, id int64) (Link, error)
	GetLinkByOriginalUrl(ctx context.Context, originalUrl string) (Link, error)
	GetLinkByReallyLongPath(ctx context.Context, reallyLongPath string) (Link, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
}

var _ Querier = (*Queries)(nil)
