// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	DeleteLink(ctx context.Context, id int64) error
	GetLink(ctx context.Context, id int64) (Link, error)
	GetLinkByReallyLongUrl(ctx context.Context, reallyLongUrl string) (Link, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
